---
title: "EDA in Python with klib"
description: |
  The klib package can make EDA using Python easier and fun!
author:
  - name: Abhijit Dasgupta
date: 2022-02-20
output:
  distill::distill_article:
    self_contained: false
draft: true
categories:
  - Python
  - dataviz
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(reticulate)
reticulate::use_condaenv('anly503', required = TRUE)
```

> This post is a distillation of the **klib** posts found [here](https://medium.com/towards-data-science/speed-up-your-data-cleaning-and-preprocessing-with-klib-97191d320f80) and [here](https://medium.com/towards-data-science/data-preparation-with-klib-ec4add15303a). Both are [Medium](https://medium.com) posts and might be behind a paywall for you. I discovered this package though colleagues at work who were using this for data cleaning and some EDA

The [**klib**](https://klib.readthedocs.io/en/latest/examples.html) package is 
meant to make data cleaning, visualization and some EDA easier on **pandas** `DataFrame`
objects. It provides a set of functions that can be gainfully utilized at the 
beginning of a data science project both for personal understanding and to 
provide visualizations of the data.

We will be using the `msleep` data from R's **ggplot2** package. This can be 
accessed in Python as a **pandas** `DataFrame` using the **rdatasets** package.

```{python, echo=TRUE}
import pandas as pd
from rdatasets import data
import matplotlib.pyplot as plt
import klib

msleep = data("ggplot2", "msleep")
msleep.head()
```

## Data quality: Missing values

You can create a heatmap of your data that looks at the missing value structure 
in your data. This is very useful for looking at the extent of missing data, 
missing data patterns, and some statistics that can help you judge whether 
you need to do something about missing data.

```{python, echo=T}
klib.missingval_plot(msleep);
plt.show()
```

## Data quality: distributions

**klib** has nice functions for visualizing distributions of both
categorical and continuous variables in a dataset. 

### Categorical variables

```{python, echo=T}
klib.cat_plot(msleep);
plt.show()
```

```{python, echo=T, eval=F}
ax = klib.dist_plot(msleep['sleep_total']);
plt.show(ax[0])
```


